[package]
name = "hello_vulkan_rt"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.10"
env_logger = "0.11.8"
glam = {version = "0.30.5", features = ["bytemuck"]}
lazy_vulkan.path = "../lazy_vulkan"
lazy_vulkan_gltf = { version = "0.1.0", path = "../lazy_vulkan_gltf" }
log = "0.4.28"
winit = "0.30.12"
