#version 460 core
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT tlas;
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outImage;
layout(push_constant) uniform Registers {
    mat4 viewInverse;
    mat4 projInverse;
} registers;

layout(location = 0) rayPayloadEXT vec3 payload;

void main() {
    const vec2 pixelCentre = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCentre / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 origin = registers.viewInverse * vec4(0, 0, 0, 1);
    vec4 target = registers.projInverse * vec4(d.x, d.y, 1, 1);
    vec4 direction = registers.viewInverse * vec4(normalize(target.xyz), 0);

    uint rayFlags = gl_RayFlagsOpaqueEXT;
    float tMin = 0.001;
    float tMax = 10000.0;

    traceRayEXT(
        tlas,
        rayFlags,
        0xFF,
        0,
        0,
        0,
        origin.xyz,
        tMin,
        direction.xyz,
        tMax,
        0
    );

    imageStore(outImage, ivec2(gl_LaunchIDEXT.xy), vec4(payload, 1));
}
